import { z } from "zod";

// ─── Variant Attribute ────────────────────────────────────────────────────────
const variantAttributeSchema = z.object({
  attribute_name: z.string().min(1, "Attribute name is required"),
  attribute_value: z.string().min(1, "Attribute value is required"),
});

// ─── Product Image (file upload) ──────────────────────────────────────────────
const variantImageSchema = z.object({
  file: z
    .instanceof(File, { message: "Must be a valid file" })
    .refine((f) => f.size <= 5 * 1024 * 1024, "Image must be under 5 MB")
    .refine(
      (f) => ["image/jpeg", "image/png", "image/webp", "image/gif"].includes(f.type),
      "Only JPEG, PNG, WebP, or GIF allowed"
    ),
  is_primary: z.boolean(),
  sort_order: z.number().int().min(0),
  // preview is a local blob URL — used for UI display only, not persisted
  preview: z.string(),
});

// ─── Product Variant ──────────────────────────────────────────────────────────
// SKU is excluded — auto-generated by Supabase on insert
const productVariantSchema = z.object({
  price: z
    .number( "Price must be a number" )
    .min(0, "Price must be at least 0"),
  stock: z
    .number( "Stock must be a number" )
    .int("Stock must be a whole number")
    .min(0, "Stock must be at least 0"),
  is_active: z.boolean(),
  attributes: z
    .array(variantAttributeSchema)
    .min(1, "At least one attribute (e.g. color, size) is required"),
  images: z.array(variantImageSchema),
});

// ─── Product Detail ───────────────────────────────────────────────────────────
const productDetailSchema = z.object({
  attribute_name: z.string().min(1, "Detail name is required"),
  attribute_value: z.string().min(1, "Detail value is required"),
  sort_order: z.number().int().min(0),
});

// ─── Root: Add Product ────────────────────────────────────────────────────────
export const addProductSchema = z.object({
  // ── products table ──────────────────────────────────────────────────────────
  name: z.string().min(1, "Product name is required").max(255, "Name is too long"),
  description: z.string().optional(),
  category_id: z
    .number( "Please select a category" )
    .int()
    .positive("Please select a category"),
  slug: z
    .string()
    .min(1, "Slug is required")
    .regex(
      /^[a-z0-9]+(?:-[a-z0-9]+)*$/,
      "Slug must be lowercase letters, numbers, and hyphens only"
    ),
  discount: z
    .number("Discount must be a number" )
    .min(0, "Discount cannot be negative")
    .max(100, "Discount cannot exceed 100%")
    .nullable()
    .optional(),
  wholesale: z.boolean(),
  is_active: z.boolean(),
  type: z.string().min(1, "Product type is required"),

  // ── product_variants ────────────────────────────────────────────────────────
  variants: z.array(productVariantSchema).min(1, "At least one variant is required"),

  // ── product_details ─────────────────────────────────────────────────────────
  details: z.array(productDetailSchema),
});

// ─── Inferred Types ───────────────────────────────────────────────────────────
export type AddProductFormValues = z.infer<typeof addProductSchema>;
export type ProductVariantValues = z.infer<typeof productVariantSchema>;
export type VariantImageValues = z.infer<typeof variantImageSchema>;
export type VariantAttributeValues = z.infer<typeof variantAttributeSchema>;
export type ProductDetailValues = z.infer<typeof productDetailSchema>;